version: '3.8'

services:
  api:
    build: .
    container_name: audio-mlops-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./temp_storage:/app/temp_storage # volume mapping for debugging (optional)
    restart: unless-stopped
    # CPU limiting can be added here if needed to heavily restrict resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 2G
